WITH source_data AS (
    SELECT *
    FROM {{
        source('ercot_raw_60_day_disclosures', '60_day_dam_disclosure_dam_gen_resource_as_offers')
        }}
)

SELECT
    "Time" AS "time", -- noqa
    "Interval Start" AS interval_start,
    "Interval End" AS interval_end,
    "QSE" AS "qse", -- noqa
    "DME" AS "dme", -- noqa
    "Generation Resource Name" AS generation_resource_name,
    "Multi-Hour Block Flag" AS multi_hour_block_flag,
    "BLOCK INDICATOR1" AS block_indicator1,
    "PRICE1 RRSPFR" AS price1_rrspfr,
    "PRICE1 RRSFFR" AS price1_rrsffr,
    "PRICE1 RRSUFR" AS price1_rrsufr,
    "PRICE1 ECRS" AS price1_ecrs,
    "PRICE1 OFFEC" AS price1_offec,
    "PRICE1 ONLINE NONSPIN" AS price1_online_nonspin,
    "PRICE1 REGUP" AS price1_regup,
    "PRICE1 REGDOWN" AS price1_regdown,
    "PRICE1 OFFLINE NONSPIN" AS price1_offline_nonspin,
    "QUANTITY MW1" AS quantity_mw1,
    "BLOCK INDICATOR2" AS block_indicator2,
    "PRICE2 RRSPFR" AS price2_rrspfr,
    "PRICE2 RRSFFR" AS price2_rrsffr,
    "PRICE2 RRSUFR" AS price2_rrsufr,
    "PRICE2 ECRS" AS price2_ecrs,
    "PRICE2 OFFEC" AS price2_offec,
    "PRICE2 ONLINE NONSPIN" AS price2_online_nonspin,
    "PRICE2 REGUP" AS price2_regup,
    "PRICE2 REGDOWN" AS price2_regdown,
    "PRICE2 OFFLINE NONSPIN" AS price2_offline_nonspin,
    "QUANTITY MW2" AS quantity_mw2,
    "BLOCK INDICATOR3" AS block_indicator3,
    "PRICE3 RRSPFR" AS price3_rrspfr,
    "PRICE3 RRSFFR" AS price3_rrsffr,
    "PRICE3 RRSUFR" AS price3_rrsufr,
    "PRICE3 ECRS" AS price3_ecrs,
    "PRICE3 OFFEC" AS price3_offec,
    "PRICE3 ONLINE NONSPIN" AS price3_online_nonspin,
    "PRICE3 REGUP" AS price3_regup,
    "PRICE3 REGDOWN" AS price3_regdown,
    "PRICE3 OFFLINE NONSPIN" AS price3_offline_nonspin,
    "QUANTITY MW3" AS quantity_mw3,
    "BLOCK INDICATOR4" AS block_indicator4,
    "PRICE4 RRSPFR" AS price4_rrspfr,
    "PRICE4 RRSFFR" AS price4_rrsffr,
    "PRICE4 RRSUFR" AS price4_rrsufr,
    "PRICE4 ECRS" AS price4_ecrs,
    "PRICE4 OFFEC" AS price4_offec,
    "PRICE4 ONLINE NONSPIN" AS price4_online_nonspin,
    "PRICE4 REGUP" AS price4_regup,
    "PRICE4 REGDOWN" AS price4_regdown,
    "PRICE4 OFFLINE NONSPIN" AS price4_offline_nonspin,
    "QUANTITY MW4" AS quantity_mw4,
    "BLOCK INDICATOR5" AS block_indicator5,
    "PRICE5 RRSPFR" AS price5_rrspfr,
    "PRICE5 RRSFFR" AS price5_rrsffr,
    "PRICE5 RRSUFR" AS price5_rrsufr,
    "PRICE5 ECRS" AS price5_ecrs,
    "PRICE5 OFFEC" AS price5_offec,
    "PRICE5 ONLINE NONSPIN" AS price5_online_nonspin,
    "PRICE5 REGUP" AS price5_regup,
    "PRICE5 REGDOWN" AS price5_regdown,
    "PRICE5 OFFLINE NONSPIN" AS price5_offline_nonspin,
    "QUANTITY MW5" AS quantity_mw5,
    load_date
FROM source_data
