WITH source_data AS (
    SELECT *
    FROM {{
        source('ercot_raw_60_day_disclosures', '60_day_sced_disclosure_sced_gen_resource')
        }}
)

SELECT
    "Interval Start" AS interval_start,
    "Interval End" AS interval_end,
    "SCED Time Stamp" AS sced_time_stamp,
    "Repeated Hour Flag" AS repeated_hour_flag,
    "QSE" AS qse,
    "DME" AS dme,
    "Resource Name" AS resource_name,
    "Resource Type" AS resource_type,
    "SCED1 Curve-MW1" AS sced1_curve_mw1,
    "SCED1 Curve-Price1" AS sced1_curve_price1,
    "SCED1 Curve-MW2" AS sced1_curve_mw2,
    "SCED1 Curve-Price2" AS sced1_curve_price2,
    "SCED1 Curve-MW3" AS sced1_curve_mw3,
    "SCED1 Curve-Price3" AS sced1_curve_price3,
    "SCED1 Curve-MW4" AS sced1_curve_mw4,
    "SCED1 Curve-Price4" AS sced1_curve_price4,
    "SCED1 Curve-MW5" AS sced1_curve_mw5,
    "SCED1 Curve-Price5" AS sced1_curve_price5,
    "SCED1 Curve-MW6" AS sced1_curve_mw6,
    "SCED1 Curve-Price6" AS sced1_curve_price6,
    "SCED1 Curve-MW7" AS sced1_curve_mw7,
    "SCED1 Curve-Price7" AS sced1_curve_price7,
    "SCED1 Curve-MW8" AS sced1_curve_mw8,
    "SCED1 Curve-Price8" AS sced1_curve_price8,
    "SCED1 Curve-MW9" AS sced1_curve_mw9,
    "SCED1 Curve-Price9" AS sced1_curve_price9,
    "SCED1 Curve-MW10" AS sced1_curve_mw10,
    "SCED1 Curve-Price10" AS sced1_curve_price10,
    "SCED1 Curve-MW11" AS sced1_curve_mw11,
    "SCED1 Curve-Price11" AS sced1_curve_price11,
    "SCED1 Curve-MW12" AS sced1_curve_mw12,
    "SCED1 Curve-Price12" AS sced1_curve_price12,
    "SCED1 Curve-MW13" AS sced1_curve_mw13,
    "SCED1 Curve-Price13" AS sced1_curve_price13,
    "SCED1 Curve-MW14" AS sced1_curve_mw14,
    "SCED1 Curve-Price14" AS sced1_curve_price14,
    "SCED1 Curve-MW15" AS sced1_curve_mw15,
    "SCED1 Curve-Price15" AS sced1_curve_price15,
    "SCED1 Curve-MW16" AS sced1_curve_mw16,
    "SCED1 Curve-Price16" AS sced1_curve_price16,
    "SCED1 Curve-MW17" AS sced1_curve_mw17,
    "SCED1 Curve-Price17" AS sced1_curve_price17,
    "SCED1 Curve-MW18" AS sced1_curve_mw18,
    "SCED1 Curve-Price18" AS sced1_curve_price18,
    "SCED1 Curve-MW19" AS sced1_curve_mw19,
    "SCED1 Curve-Price19" AS sced1_curve_price19,
    "SCED1 Curve-MW20" AS sced1_curve_mw20,
    "SCED1 Curve-Price20" AS sced1_curve_price20,
    "SCED1 Curve-MW21" AS sced1_curve_mw21,
    "SCED1 Curve-Price21" AS sced1_curve_price21,
    "SCED1 Curve-MW22" AS sced1_curve_mw22,
    "SCED1 Curve-Price22" AS sced1_curve_price22,
    "SCED1 Curve-MW23" AS sced1_curve_mw23,
    "SCED1 Curve-Price23" AS sced1_curve_price23,
    "SCED1 Curve-MW24" AS sced1_curve_mw24,
    "SCED1 Curve-Price24" AS sced1_curve_price24,
    "SCED1 Curve-MW25" AS sced1_curve_mw25,
    "SCED1 Curve-Price25" AS sced1_curve_price25,
    "SCED1 Curve-MW26" AS sced1_curve_mw26,
    "SCED1 Curve-Price26" AS sced1_curve_price26,
    "SCED1 Curve-MW27" AS sced1_curve_mw27,
    "SCED1 Curve-Price27" AS sced1_curve_price27,
    "SCED1 Curve-MW28" AS sced1_curve_mw28,
    "SCED1 Curve-Price28" AS sced1_curve_price28,
    "SCED1 Curve-MW29" AS sced1_curve_mw29,
    "SCED1 Curve-Price29" AS sced1_curve_price29,
    "SCED1 Curve-MW30" AS sced1_curve_mw30,
    "SCED1 Curve-Price30" AS sced1_curve_price30,
    "SCED1 Curve-MW31" AS sced1_curve_mw31,
    "SCED1 Curve-Price31" AS sced1_curve_price31,
    "SCED1 Curve-MW32" AS sced1_curve_mw32,
    "SCED1 Curve-Price32" AS sced1_curve_price32,
    "SCED1 Curve-MW33" AS sced1_curve_mw33,
    "SCED1 Curve-Price33" AS sced1_curve_price33,
    "SCED1 Curve-MW34" AS sced1_curve_mw34,
    "SCED1 Curve-Price34" AS sced1_curve_price34,
    "SCED1 Curve-MW35" AS sced1_curve_mw35,
    "SCED1 Curve-Price35" AS sced1_curve_price35,
    "SCED2 Curve-MW1" AS sced2_curve_mw1,
    "SCED2 Curve-Price1" AS sced2_curve_price1,
    "SCED2 Curve-MW2" AS sced2_curve_mw2,
    "SCED2 Curve-Price2" AS sced2_curve_price2,
    "SCED2 Curve-MW3" AS sced2_curve_mw3,
    "SCED2 Curve-Price3" AS sced2_curve_price3,
    "SCED2 Curve-MW4" AS sced2_curve_mw4,
    "SCED2 Curve-Price4" AS sced2_curve_price4,
    "SCED2 Curve-MW5" AS sced2_curve_mw5,
    "SCED2 Curve-Price5" AS sced2_curve_price5,
    "SCED2 Curve-MW6" AS sced2_curve_mw6,
    "SCED2 Curve-Price6" AS sced2_curve_price6,
    "SCED2 Curve-MW7" AS sced2_curve_mw7,
    "SCED2 Curve-Price7" AS sced2_curve_price7,
    "SCED2 Curve-MW8" AS sced2_curve_mw8,
    "SCED2 Curve-Price8" AS sced2_curve_price8,
    "SCED2 Curve-MW9" AS sced2_curve_mw9,
    "SCED2 Curve-Price9" AS sced2_curve_price9,
    "SCED2 Curve-MW10" AS sced2_curve_mw10,
    "SCED2 Curve-Price10" AS sced2_curve_price10,
    "SCED2 Curve-MW11" AS sced2_curve_mw11,
    "SCED2 Curve-Price11" AS sced2_curve_price11,
    "SCED2 Curve-MW12" AS sced2_curve_mw12,
    "SCED2 Curve-Price12" AS sced2_curve_price12,
    "SCED2 Curve-MW13" AS sced2_curve_mw13,
    "SCED2 Curve-Price13" AS sced2_curve_price13,
    "SCED2 Curve-MW14" AS sced2_curve_mw14,
    "SCED2 Curve-Price14" AS sced2_curve_price14,
    "SCED2 Curve-MW15" AS sced2_curve_mw15,
    "SCED2 Curve-Price15" AS sced2_curve_price15,
    "SCED2 Curve-MW16" AS sced2_curve_mw16,
    "SCED2 Curve-Price16" AS sced2_curve_price16,
    "SCED2 Curve-MW17" AS sced2_curve_mw17,
    "SCED2 Curve-Price17" AS sced2_curve_price17,
    "SCED2 Curve-MW18" AS sced2_curve_mw18,
    "SCED2 Curve-Price18" AS sced2_curve_price18,
    "SCED2 Curve-MW19" AS sced2_curve_mw19,
    "SCED2 Curve-Price19" AS sced2_curve_price19,
    "SCED2 Curve-MW20" AS sced2_curve_mw20,
    "SCED2 Curve-Price20" AS sced2_curve_price20,
    "SCED2 Curve-MW21" AS sced2_curve_mw21,
    "SCED2 Curve-Price21" AS sced2_curve_price21,
    "SCED2 Curve-MW22" AS sced2_curve_mw22,
    "SCED2 Curve-Price22" AS sced2_curve_price22,
    "SCED2 Curve-MW23" AS sced2_curve_mw23,
    "SCED2 Curve-Price23" AS sced2_curve_price23,
    "SCED2 Curve-MW24" AS sced2_curve_mw24,
    "SCED2 Curve-Price24" AS sced2_curve_price24,
    "SCED2 Curve-MW25" AS sced2_curve_mw25,
    "SCED2 Curve-Price25" AS sced2_curve_price25,
    "SCED2 Curve-MW26" AS sced2_curve_mw26,
    "SCED2 Curve-Price26" AS sced2_curve_price26,
    "SCED2 Curve-MW27" AS sced2_curve_mw27,
    "SCED2 Curve-Price27" AS sced2_curve_price27,
    "SCED2 Curve-MW28" AS sced2_curve_mw28,
    "SCED2 Curve-Price28" AS sced2_curve_price28,
    "SCED2 Curve-MW29" AS sced2_curve_mw29,
    "SCED2 Curve-Price29" AS sced2_curve_price29,
    "SCED2 Curve-MW30" AS sced2_curve_mw30,
    "SCED2 Curve-Price30" AS sced2_curve_price30,
    "SCED2 Curve-MW31" AS sced2_curve_mw31,
    "SCED2 Curve-Price31" AS sced2_curve_price31,
    "SCED2 Curve-MW32" AS sced2_curve_mw32,
    "SCED2 Curve-Price32" AS sced2_curve_price32,
    "SCED2 Curve-MW33" AS sced2_curve_mw33,
    "SCED2 Curve-Price33" AS sced2_curve_price33,
    "SCED2 Curve-MW34" AS sced2_curve_mw34,
    "SCED2 Curve-Price34" AS sced2_curve_price34,
    "SCED2 Curve-MW35" AS sced2_curve_mw35,
    "SCED2 Curve-Price35" AS sced2_curve_price35,
    "Output Schedule" AS output_schedule,
    "HSL" AS hsl,
    "HASL" AS hasl,
    "HDL" AS hdl,
    "LSL" AS lsl,
    "LASL" AS lasl,
    "LDL" AS ldl,
    "Telemetered Resource Status" AS telemetered_resource_status,
    "Base Point" AS base_point,
    "Telemetered Net Output" AS telemetered_net_output,
    "Ancillary Service REGUP" AS ancillary_service_regup,
    "Ancillary Service REGDN" AS ancillary_service_regdn,
    "Ancillary Service RRS" AS ancillary_service_rrs,
    "Ancillary Service RRSFFR" AS ancillary_service_rrsffr,
    "Ancillary Service NSRS" AS ancillary_service_nsrs,
    "Ancillary Service ECRS" AS ancillary_service_ecrs,
    "Bid_Type" AS bid_type,
    "Start Up Cold Offer" AS start_up_cold_offer,
    "Start Up Hot Offer" AS start_up_hot_offer,
    "Start Up Inter Offer" AS start_up_inter_offer,
    "Min Gen Cost" AS min_gen_cost,
    "Submitted TPO-MW1" AS submitted_tpo_mw1,
    "Submitted TPO-Price1" AS submitted_tpo_price1,
    "Submitted TPO-MW2" AS submitted_tpo_mw2,
    "Submitted TPO-Price2" AS submitted_tpo_price2,
    "Submitted TPO-MW3" AS submitted_tpo_mw3,
    "Submitted TPO-Price3" AS submitted_tpo_price3,
    "Submitted TPO-MW4" AS submitted_tpo_mw4,
    "Submitted TPO-Price4" AS submitted_tpo_price4,
    "Submitted TPO-MW5" AS submitted_tpo_mw5,
    "Submitted TPO-Price5" AS submitted_tpo_price5,
    "Submitted TPO-MW6" AS submitted_tpo_mw6,
    "Submitted TPO-Price6" AS submitted_tpo_price6,
    "Submitted TPO-MW7" AS submitted_tpo_mw7,
    "Submitted TPO-Price7" AS submitted_tpo_price7,
    "Submitted TPO-MW8" AS submitted_tpo_mw8,
    "Submitted TPO-Price8" AS submitted_tpo_price8,
    "Submitted TPO-MW9" AS submitted_tpo_mw9,
    "Submitted TPO-Price9" AS submitted_tpo_price9,
    "Submitted TPO-MW10" AS submitted_tpo_mw10,
    "Submitted TPO-Price10" AS submitted_tpo_price10,
    "Proxy Extension" AS proxy_extension,
    load_date
FROM source_data
