WITH source_data AS (
    SELECT
        *
    FROM {{ source('ercot_raw_60_day_disclosures', '60_day_sced_disclosure_sced_load_resource') }}
)

SELECT
    "Interval Start",
    "Interval End",
    "SCED Time Stamp",
    "Repeated Hour Flag",
    "QSE",
    "DME",
    "Resource Name",
    "Telemetered Resource Status",
    "Max Power Consumption",
    "Low Power Consumption",
    "Real Power Consumption",
    "AS Responsibility for RRS",
    "AS Responsibility for RRSFFR",
    "AS Responsibility for NonSpin",
    "AS Responsibility for RegUp",
    "AS Responsibility for RegDown",
    "AS Responsibility for ECRS",
    "SCED Bid to Buy Curve-MW1",
    "SCED Bid to Buy Curve-Price1",
    "SCED Bid to Buy Curve-MW2",
    "SCED Bid to Buy Curve-Price2",
    "SCED Bid to Buy Curve-MW3",
    "SCED Bid to Buy Curve-Price3",
    "SCED Bid to Buy Curve-MW4",
    "SCED Bid to Buy Curve-Price4",
    "SCED Bid to Buy Curve-MW5",
    "SCED Bid to Buy Curve-Price5",
    "SCED Bid to Buy Curve-MW6",
    "SCED Bid to Buy Curve-Price6",
    "SCED Bid to Buy Curve-MW7",
    "SCED Bid to Buy Curve-Price7",
    "SCED Bid to Buy Curve-MW8",
    "SCED Bid to Buy Curve-Price8",
    "SCED Bid to Buy Curve-MW9",
    "SCED Bid to Buy Curve-Price9",
    "SCED Bid to Buy Curve-MW10",
    "SCED Bid to Buy Curve-Price10",
    "HASL",
    "HDL",
    "LASL",
    "LDL",
    "Base Point",
    "load_date"
FROM source_data
