version: 2

sources:
  - name: ercot_raw
    schema: main
    tables:
      - name: 60_day_disclosures
        external:
          location: "data/raw/ercot/60_day_disclosures/*.parquet"
          format: parquet