name: 'grid_data'
profile: 'grid_data'
config-version: 2

model-paths: ["models"]
target-path: "target"
clean-targets: ["target"]

vars:
  raw_data_path: '../data/raw'

models:
  grid_data:
    staging:
      +materialized: table
    intermediate:
      +materialized: table
    analytics:
      +materialized: table