name: 'grid_data'
profile: 'grid_data'
config-version: 2

model-paths: ["models"]
target-path: "target"
clean-targets: ["target"]

models:
  grid_data:
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    analytics:
      +materialized: table