name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pre-commit install
          
      - name: Run pre-commit
        run: pre-commit run --all-files
        
      - name: Run dbt tests
        run: |
          cd dbt_project
          dbt test